import { ThemeColorSet } from '@/types';

export const themeFonts: Record<string, { heading: string; body: string }> = {
  'fantasy-parchment': { heading: 'var(--font-cinzel)', body: 'var(--font-plus-jakarta)' },
  'gothic-horror': { heading: 'var(--font-uncial-antiqua)', body: 'var(--font-lora)' },
  'heroic': { heading: 'var(--font-marcellus)', body: 'var(--font-spectral)' },
  'gritty': { heading: 'var(--font-special-elite)', body: 'var(--font-courier-prime)' },
  'whimsical': { heading: 'var(--font-rancho)', body: 'var(--font-fredoka)' },
  'cyberpunk': { heading: 'var(--font-oxanium)', body: 'var(--font-share-tech-mono)' },
  'space-scifi': { heading: 'var(--font-orbitron)', body: 'var(--font-rajdhani)' },
  'pirate': { heading: 'var(--font-berkshire-swash)', body: 'var(--font-eb-garamond)' },
  'horror': { heading: 'var(--font-creepster)', body: 'var(--font-crimson-text)' },
  'lovecraftian': { heading: 'var(--font-metamorphous)', body: 'var(--font-syne)' },
  'fey': { heading: 'var(--font-macondo)', body: 'var(--font-quicksand)' },
  'underworld': { heading: 'var(--font-russo-one)', body: 'var(--font-chivo)' },
  'steampunk': { heading: 'var(--font-rye)', body: 'var(--font-pt-mono)' },
};

export const themePresets: Record<string, { light: ThemeColorSet; dark: ThemeColorSet }> = {
  'fantasy-parchment': {
    light: {
      surface: '#fff8f0',
      surfaceDim: '#f0d991',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#fff3d5',
      surfaceContainer: '#ffedba',
      surfaceContainerHigh: '#fbf2cd',
      surfaceContainerHighest: '#f7e1a0',
      primary: '#8d34b4',
      primaryContainer: '#e8aaff',
      primaryDim: '#8025a6',
      onSurface: '#3e3101',
      outlineVariant: '#c4b174',
      secondary: '#954b00',
      secondaryContainer: '#ffdcc5',
      onSecondaryContainer: '#814000',
      tertiary: '#2d6a4f',
      tertiaryContainer: '#beffdc',
      radiusContainer: '2.5rem 1rem 2.5rem 1rem',
      borderContainer: '1px solid rgba(196,177,116,0.2)',
      shadowContainer: '0 15px 45px rgba(62,49,1,0.05)',
      transitionSpeed: '0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      hoverTransform: 'translateY(-6px)',
      hoverShadow: '0 25px 60px rgba(62,49,1,0.1)'
    },
    dark: {
      surface: '#2c2317',
      surfaceDim: '#1e170d',
      surfaceContainerLowest: '#110b05',
      surfaceContainerLow: '#221910',
      surfaceContainer: '#302519',
      surfaceContainerHigh: '#3c2f21',
      surfaceContainerHighest: '#473a2b',
      primary: '#d59df4',
      primaryContainer: '#67168c',
      primaryDim: '#b17ad2',
      onSurface: '#f5eedd',
      outlineVariant: '#6e6242',
      secondary: '#ffb68c',
      secondaryContainer: '#632d00',
      onSecondaryContainer: '#ffdcc5',
      tertiary: '#72d6a4',
      tertiaryContainer: '#0e4a30',
      radiusContainer: '2.5rem 1rem 2.5rem 1rem',
      borderContainer: '1px solid rgba(110,98,66,0.3)',
      shadowContainer: '0 15px 45px rgba(0,0,0,0.3)',
      transitionSpeed: '0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      hoverTransform: 'translateY(-6px)',
      hoverShadow: '0 25px 60px rgba(0,0,0,0.5)'
    }
  },
  'gothic-horror': {
    light: {
      surface: '#f5f0eb',
      surfaceDim: '#d9cfc6',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#edd9d9',
      surfaceContainer: '#dfc2c2',
      surfaceContainerHigh: '#d0a7a7',
      surfaceContainerHighest: '#be8c8c',
      primary: '#4a0e17',
      primaryContainer: '#ffd8dc',
      primaryDim: '#3a0209',
      onSurface: '#2b1d1d',
      outlineVariant: '#a38b8b',
      secondary: '#5c3838',
      secondaryContainer: '#ffdad8',
      onSecondaryContainer: '#3c1515',
      tertiary: '#484a3a',
      tertiaryContainer: '#e2e7c3',
      radiusContainer: '4px',
      borderContainer: '1px solid var(--outline-variant)',
      shadowContainer: '0 10px 40px rgba(0,0,0,0.06)',
      transitionSpeed: '0.4s ease-in-out',
      hoverTransform: 'translateY(-4px)',
      hoverShadow: '0 20px 50px rgba(74,14,23,0.12)',
      hoverBorderColor: 'var(--primary)'
    },
    dark: {
      surface: '#171212',
      surfaceDim: '#0a0808',
      surfaceContainerLowest: '#030202',
      surfaceContainerLow: '#231d1d',
      surfaceContainer: '#2d2525',
      surfaceContainerHigh: '#393030',
      surfaceContainerHighest: '#463b3b',
      primary: '#851414',
      primaryContainer: '#620007',
      primaryDim: '#ff8985',
      onSurface: '#e0ccbe',
      outlineVariant: '#564242',
      secondary: '#dfbebe',
      secondaryContainer: '#5c3f3f',
      onSecondaryContainer: '#ffdad8',
      tertiary: '#b7c79e',
      tertiaryContainer: '#2c371a',
      radiusContainer: '4px',
      borderContainer: '1px solid var(--outline-variant)',
      shadowContainer: '0 10px 40px rgba(0,0,0,0.5)',
      transitionSpeed: '0.4s ease-in-out',
      hoverTransform: 'translateY(-4px)',
      hoverShadow: '0 20px 50px rgba(74,14,23,0.3)',
      hoverBorderColor: 'var(--primary)'
    }
  },
  'cyberpunk': {
    light: {
      surface: '#fbfbff',
      surfaceDim: '#e8e8f5',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f2f2fa',
      surfaceContainer: '#e5e5f0',
      surfaceContainerHigh: '#d5d5e5',
      surfaceContainerHighest: '#c5c5da',
      primary: '#d01cbf',
      primaryContainer: '#ffd6fa',
      primaryDim: '#b00b9e',
      onSurface: '#14002e',
      outlineVariant: '#a09cbd',
      secondary: '#0062a3',
      secondaryContainer: '#d4e3ff',
      onSecondaryContainer: '#001c34',
      tertiary: '#008b62',
      tertiaryContainer: '#c5ffe2',
      radiusContainer: '0px',
      borderContainer: '1px solid var(--primary)',
      shadowContainer: '0 0 10px rgba(208,28,191,0.05)',
      clipPathContainer: 'polygon(0 0, calc(100% - 15px) 0, 100% 15px, 100% 100%, 15% 100%, 0 calc(100% - 15px))',
      transitionSpeed: '0.1s ease',
      hoverTransform: 'none',
      hoverShadow: '0 0 20px var(--primary)',
      hoverBorderColor: 'var(--primary)'
    },
    dark: {
      surface: '#05050e',
      surfaceDim: '#010105',
      surfaceContainerLowest: '#000000',
      surfaceContainerLow: '#0e0e1b',
      surfaceContainer: '#19192c',
      surfaceContainerHigh: '#26263b',
      surfaceContainerHighest: '#36364c',
      primary: '#39ff14',
      primaryContainer: '#006400',
      primaryDim: '#8eff62',
      onSurface: '#ff007f',
      outlineVariant: '#46465c',
      secondary: '#00e5ff',
      secondaryContainer: '#004a57',
      onSecondaryContainer: '#caf6ff',
      tertiary: '#ffff00',
      tertiaryContainer: '#555500',
      radiusContainer: '0px',
      borderContainer: '1px solid var(--primary)',
      shadowContainer: '0 0 10px rgba(57,255,20,0.1)',
      clipPathContainer: 'polygon(0 0, calc(100% - 15px) 0, 100% 15px, 100% 100%, 15% 100%, 0 calc(100% - 15px))',
      transitionSpeed: '0.1s ease',
      hoverTransform: 'none',
      hoverShadow: '0 0 20px var(--primary)',
      hoverBorderColor: 'var(--primary)'
    }
  },
  'space-scifi': {
    light: {
      surface: '#f0f4f8',
      surfaceDim: '#d0dae5',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#e5ecf2',
      surfaceContainer: '#dbe3ea',
      surfaceContainerHigh: '#ccd5de',
      surfaceContainerHighest: '#bcc7d1',
      primary: '#0096c7',
      primaryContainer: '#caf0f8',
      primaryDim: '#0077b6',
      onSurface: '#023e8a',
      outlineVariant: '#90e0ef',
      secondary: '#48cae4',
      secondaryContainer: '#ade8f4',
      onSecondaryContainer: '#03045e',
      tertiary: '#90e0ef',
      tertiaryContainer: '#e0f7fa',
      radiusContainer: '1rem',
      borderContainer: '1px solid var(--primary)',
      shadowContainer: '0 0 15px rgba(0,150,199,0.05)',
      clipPathContainer: 'polygon(15px 0, 100% 0, 100% calc(100% - 15px), calc(100% - 15px) 100%, 0 100%, 0 15px)',
      transitionSpeed: '0.2s cubic-bezier(0.25, 0.8, 0.25, 1)',
      hoverTransform: 'scale(1.01)',
      hoverShadow: '0 0 25px rgba(0,150,199,0.2)'
    },
    dark: {
      surface: '#0b0f19',
      surfaceDim: '#03050a',
      surfaceContainerLowest: '#010103',
      surfaceContainerLow: '#121926',
      surfaceContainer: '#1c2536',
      surfaceContainerHigh: '#28334a',
      surfaceContainerHighest: '#384764',
      primary: '#00e5ff',
      primaryContainer: '#003e47',
      primaryDim: '#70f2ff',
      onSurface: '#e2e8f0',
      outlineVariant: '#2e3a52',
      secondary: '#0d9488',
      secondaryContainer: '#115e59',
      onSecondaryContainer: '#99f6e4',
      tertiary: '#2563eb',
      tertiaryContainer: '#1d4ed8',
      radiusContainer: '1rem',
      borderContainer: '1px solid var(--primary)',
      shadowContainer: '0 0 15px rgba(0,229,255,0.1)',
      clipPathContainer: 'polygon(15px 0, 100% 0, 100% calc(100% - 15px), calc(100% - 15px) 100%, 0 100%, 0 15px)',
      transitionSpeed: '0.2s cubic-bezier(0.25, 0.8, 0.25, 1)',
      hoverTransform: 'scale(1.01)',
      hoverShadow: '0 0 25px rgba(0,229,255,0.25)'
    }
  },
  'whimsical': {
    light: {
      surface: '#fdf9ff',
      surfaceDim: '#f0deff',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f7ebff',
      surfaceContainer: '#ebd8fd',
      surfaceContainerHigh: '#dfbeff',
      surfaceContainerHighest: '#cca2ff',
      primary: '#a855f7',
      primaryContainer: '#f3e8ff',
      primaryDim: '#8922e8',
      onSurface: '#3e166b',
      outlineVariant: '#c084fc',
      secondary: '#ec4899',
      secondaryContainer: '#fce7f3',
      onSecondaryContainer: '#831843',
      tertiary: '#10b981',
      tertiaryContainer: '#d1fae5',
      radiusContainer: '2.5rem',
      borderContainer: 'none',
      shadowContainer: '0 12px 30px rgba(168,85,247,0.04)',
      transitionSpeed: '0.35s cubic-bezier(0.175, 0.885, 0.32, 1.4)',
      hoverTransform: 'scale(1.05) translateY(-5px)',
      hoverShadow: '0 20px 45px rgba(168,85,247,0.14)'
    },
    dark: {
      surface: '#201530',
      surfaceDim: '#130a1f',
      surfaceContainerLowest: '#09030e',
      surfaceContainerLow: '#2c1e40',
      surfaceContainer: '#382850',
      surfaceContainerHigh: '#453361',
      surfaceContainerHighest: '#533e72',
      primary: '#e9d5ff',
      primaryContainer: '#4a1d82',
      primaryDim: '#d8b4fe',
      onSurface: '#faf5ff',
      outlineVariant: '#5c457d',
      secondary: '#f472b6',
      secondaryContainer: '#831843',
      onSecondaryContainer: '#fce7f3',
      tertiary: '#34d399',
      tertiaryContainer: '#064e3b',
      radiusContainer: '2.5rem',
      borderContainer: 'none',
      shadowContainer: '0 12px 30px rgba(0,0,0,0.3)',
      transitionSpeed: '0.35s cubic-bezier(0.175, 0.885, 0.32, 1.4)',
      hoverTransform: 'scale(1.05) translateY(-5px)',
      hoverShadow: '0 20px 45px rgba(233,213,255,0.15)'
    }
  },
  'gritty': {
    light: {
      surface: '#dfddd6',
      surfaceDim: '#c2bfb4',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#e9e7e1',
      surfaceContainer: '#dedbd2',
      surfaceContainerHigh: '#d2cebe',
      surfaceContainerHighest: '#c5beaa',
      primary: '#824419',
      primaryContainer: '#ffdbc2',
      primaryDim: '#5e2e0e',
      onSurface: '#242220',
      outlineVariant: '#9c9287',
      secondary: '#4f4f46',
      secondaryContainer: '#f5f5f3',
      onSecondaryContainer: '#1a1a17',
      tertiary: '#3b3b33',
      tertiaryContainer: '#ecece9',
      radiusContainer: '2px',
      borderContainer: '3px solid var(--on-surface)',
      shadowContainer: '4px 4px 0px var(--on-surface)',
      transitionSpeed: '0.1s ease',
      hoverTransform: 'translate(-2px, -2px)',
      hoverShadow: '6px 6px 0px var(--on-surface)'
    },
    dark: {
      surface: '#1d1b1a',
      surfaceDim: '#121010',
      surfaceContainerLowest: '#0a0808',
      surfaceContainerLow: '#272523',
      surfaceContainer: '#33302d',
      surfaceContainerHigh: '#3f3b38',
      surfaceContainerHighest: '#4c4844',
      primary: '#d97736',
      primaryContainer: '#6b320d',
      primaryDim: '#f09355',
      onSurface: '#eae7e5',
      outlineVariant: '#5c544d',
      secondary: '#8d8d85',
      secondaryContainer: '#33332d',
      onSecondaryContainer: '#f5f5f3',
      tertiary: '#b3b3aa',
      tertiaryContainer: '#4f4f46',
      radiusContainer: '2px',
      borderContainer: '3px solid var(--on-surface)',
      shadowContainer: '4px 4px 0px var(--on-surface)',
      transitionSpeed: '0.1s ease',
      hoverTransform: 'translate(-2px, -2px)',
      hoverShadow: '6px 6px 0px var(--on-surface)'
    }
  },
  'heroic': {
    light: {
      surface: '#fcfbf7',
      surfaceDim: '#ece8da',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f7f4e8',
      surfaceContainer: '#eddcb5',
      surfaceContainerHigh: '#e1ca94',
      surfaceContainerHighest: '#d4b474',
      primary: '#0f3a5f',
      primaryContainer: '#d4e5ff',
      primaryDim: '#002240',
      onSurface: '#111d29',
      outlineVariant: '#cbb06d',
      secondary: '#7c6a21',
      secondaryContainer: '#fef1bb',
      onSecondaryContainer: '#0f3a5f',
      tertiary: '#346b5a',
      tertiaryContainer: '#d5ece3',
      radiusContainer: '1.5rem',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 10px 30px rgba(0,0,0,0.04)',
      transitionSpeed: '0.2s ease-out',
      hoverTransform: 'scale(1.02)',
      hoverShadow: '0 15px 35px rgba(15,58,95,0.08)'
    },
    dark: {
      surface: '#0b1a30',
      surfaceDim: '#040b15',
      surfaceContainerLowest: '#02050b',
      surfaceContainerLow: '#132641',
      surfaceContainer: '#1c3455',
      surfaceContainerHigh: '#28456a',
      surfaceContainerHighest: '#365881',
      primary: '#d9a014',
      primaryContainer: '#4a3400',
      primaryDim: '#ffd260',
      onSurface: '#edf1f7',
      outlineVariant: '#385c83',
      secondary: '#bba442',
      secondaryContainer: '#2c2500',
      onSecondaryContainer: '#edf1f7',
      tertiary: '#70a597',
      tertiaryContainer: '#1b3f36',
      radiusContainer: '1.5rem',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 10px 30px rgba(0,0,0,0.4)',
      transitionSpeed: '0.2s ease-out',
      hoverTransform: 'scale(1.02)',
      hoverShadow: '0 15px 35px rgba(217,160,20,0.15)'
    }
  },
  'pirate': {
    light: {
      surface: '#faf5e8',
      surfaceDim: '#e5dcbe',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f2eae0',
      surfaceContainer: '#eddcc5',
      surfaceContainerHigh: '#e1c6a2',
      surfaceContainerHighest: '#d3aa7b',
      primary: '#9e1a1a',
      primaryContainer: '#ffd8d8',
      primaryDim: '#700909',
      onSurface: '#1a202c',
      outlineVariant: '#c8a47e',
      secondary: '#1c6265',
      secondaryContainer: '#ccf2f4',
      onSecondaryContainer: '#002022',
      tertiary: '#2d6a4f',
      tertiaryContainer: '#d8f3dc',
      radiusContainer: '2rem',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 10px 25px rgba(0,0,0,0.06)',
      transitionSpeed: '0.25s ease-out',
      hoverTransform: 'translateY(-5px)',
      hoverShadow: '0 20px 45px rgba(28,98,101,0.15)'
    },
    dark: {
      surface: '#0d1721',
      surfaceDim: '#050a10',
      surfaceContainerLowest: '#020406',
      surfaceContainerLow: '#152433',
      surfaceContainer: '#1d2f42',
      surfaceContainerHigh: '#273c54',
      surfaceContainerHighest: '#334c67',
      primary: '#ffd369',
      primaryContainer: '#4d3d00',
      primaryDim: '#ffdf92',
      onSurface: '#e4f1fe',
      outlineVariant: '#3a536b',
      secondary: '#2ecc71',
      secondaryContainer: '#14532d',
      onSecondaryContainer: '#d1fae5',
      tertiary: '#00f5d4',
      tertiaryContainer: '#005f52',
      radiusContainer: '2rem',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 10px 25px rgba(0,0,0,0.4)',
      transitionSpeed: '0.25s ease-out',
      hoverTransform: 'translateY(-5px)',
      hoverShadow: '0 20px 45px rgba(0,245,212,0.15)'
    }
  },
  'horror': {
    light: {
      surface: '#f9f6f0',
      surfaceDim: '#e0d8c8',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#edd9d5',
      surfaceContainer: '#debeb5',
      surfaceContainerHigh: '#cf9f95',
      surfaceContainerHighest: '#be7f73',
      primary: '#7f0000',
      primaryContainer: '#ffd5d5',
      primaryDim: '#550000',
      onSurface: '#111111',
      outlineVariant: '#9c7373',
      secondary: '#3d1212',
      secondaryContainer: '#ffdad6',
      onSecondaryContainer: '#350003',
      tertiary: '#212529',
      tertiaryContainer: '#e9ecef',
      radiusContainer: '2px',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 15px 35px rgba(0,0,0,0.15)',
      transitionSpeed: '0.5s ease',
      hoverTransform: 'none',
      hoverShadow: '0 0 30px rgba(127,0,0,0.2)',
      hoverBorderColor: 'var(--primary)'
    },
    dark: {
      surface: '#090808',
      surfaceDim: '#030202',
      surfaceContainerLowest: '#000000',
      surfaceContainerLow: '#1a1313',
      surfaceContainer: '#261b1b',
      surfaceContainerHigh: '#362424',
      surfaceContainerHighest: '#482f2f',
      primary: '#ff3333',
      primaryContainer: '#660000',
      primaryDim: '#ff8080',
      onSurface: '#c7c7c7',
      outlineVariant: '#563535',
      secondary: '#ef9a9a',
      secondaryContainer: '#5d101d',
      onSecondaryContainer: '#ffdadb',
      tertiary: '#adb5bd',
      tertiaryContainer: '#212529',
      radiusContainer: '2px',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 15px 35px rgba(0,0,0,0.5)',
      transitionSpeed: '0.5s ease',
      hoverTransform: 'none',
      hoverShadow: '0 0 30px rgba(255,51,51,0.25)',
      hoverBorderColor: 'var(--primary)'
    }
  },
  'lovecraftian': {
    light: {
      surface: '#edf2f0',
      surfaceDim: '#ccd9d4',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#e0ede5',
      surfaceContainer: '#cfe0d6',
      surfaceContainerHigh: '#bdceca',
      surfaceContainerHighest: '#abbeb8',
      primary: '#673ab7',
      primaryContainer: '#ede7f6',
      primaryDim: '#4a148c',
      onSurface: '#1a2c27',
      outlineVariant: '#8dafa4',
      secondary: '#00796b',
      secondaryContainer: '#e0f2f1',
      onSecondaryContainer: '#00251a',
      tertiary: '#4a148c',
      tertiaryContainer: '#f3e5f5',
      radiusContainer: '8px',
      borderContainer: '1px solid var(--outline-variant)',
      shadowContainer: '0 10px 30px rgba(0,0,0,0.06)',
      transitionSpeed: '0.4s ease-in-out',
      hoverTransform: 'scale(1.02)',
      hoverShadow: '0 0 25px rgba(103,58,183,0.2)'
    },
    dark: {
      surface: '#071415',
      surfaceDim: '#020809',
      surfaceContainerLowest: '#000000',
      surfaceContainerLow: '#102629',
      surfaceContainer: '#173539',
      surfaceContainerHigh: '#21474d',
      surfaceContainerHighest: '#2d5a62',
      primary: '#39ff14',
      primaryContainer: '#005f00',
      primaryDim: '#7cff62',
      onSurface: '#d2f7f2',
      outlineVariant: '#2a5a5e',
      secondary: '#bc34fa',
      secondaryContainer: '#4b006c',
      onSecondaryContainer: '#f7d2ff',
      tertiary: '#00f5d4',
      tertiaryContainer: '#004d41',
      radiusContainer: '8px',
      borderContainer: '1px solid var(--outline-variant)',
      shadowContainer: '0 10px 30px rgba(0,0,0,0.5)',
      transitionSpeed: '0.4s ease-in-out',
      hoverTransform: 'scale(1.02)',
      hoverShadow: '0 0 25px var(--primary)'
    }
  },
  'fey': {
    light: {
      surface: '#fff5f7',
      surfaceDim: '#fbd0db',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#ffeef1',
      surfaceContainer: '#fbd8e0',
      surfaceContainerHigh: '#f3b4c4',
      surfaceContainerHighest: '#e790a6',
      primary: '#ec4899',
      primaryContainer: '#fce7f3',
      primaryDim: '#be185d',
      onSurface: '#360c2b',
      outlineVariant: '#e0a3b2',
      secondary: '#a21caf',
      secondaryContainer: '#fae8ff',
      onSecondaryContainer: '#4a044e',
      tertiary: '#10b981',
      tertiaryContainer: '#d1fae5',
      radiusContainer: '3rem 1rem 3rem 1rem',
      borderContainer: 'none',
      shadowContainer: '0 15px 35px rgba(236,72,153,0.03)',
      transitionSpeed: '0.3s cubic-bezier(0.175, 0.885, 0.32, 1.25)',
      hoverTransform: 'translateY(-5px)',
      hoverShadow: '0 25px 50px rgba(236,72,153,0.08)'
    },
    dark: {
      surface: '#180424',
      surfaceDim: '#0d0115',
      surfaceContainerLowest: '#06000a',
      surfaceContainerLow: '#2c103e',
      surfaceContainer: '#3b1853',
      surfaceContainerHigh: '#4a2168',
      surfaceContainerHighest: '#5a2c7d',
      primary: '#f472b6',
      primaryContainer: '#5c163a',
      primaryDim: '#f9a8d4',
      onSurface: '#fae8ff',
      outlineVariant: '#5c2d7a',
      secondary: '#e879f9',
      secondaryContainer: '#5e0766',
      onSecondaryContainer: '#fae8ff',
      tertiary: '#34d399',
      tertiaryContainer: '#064e3b',
      radiusContainer: '3rem 1rem 3rem 1rem',
      borderContainer: 'none',
      shadowContainer: '0 15px 35px rgba(0,0,0,0.4)',
      transitionSpeed: '0.3s cubic-bezier(0.175, 0.885, 0.32, 1.25)',
      hoverTransform: 'translateY(-5px)',
      hoverShadow: '0 25px 50px rgba(244,114,182,0.1)'
    }
  },
  'underworld': {
    light: {
      surface: '#eae7e1',
      surfaceDim: '#cfc9bd',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#ebe7e0',
      surfaceContainer: '#dfdcd3',
      surfaceContainerHigh: '#d0cbc2',
      surfaceContainerHighest: '#c1bcb0',
      primary: '#dd6b20',
      primaryContainer: '#ffeadb',
      primaryDim: '#a64400',
      onSurface: '#1a1918',
      outlineVariant: '#a09c91',
      secondary: '#5c5240',
      secondaryContainer: '#f2eae1',
      onSecondaryContainer: '#1c1811',
      tertiary: '#403c34',
      tertiaryContainer: '#eae7e1',
      radiusContainer: '12px',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 12px 30px rgba(0,0,0,0.08)',
      transitionSpeed: '0.2s cubic-bezier(0.4, 0, 0.2, 1)',
      hoverTransform: 'scale(1.03)',
      hoverShadow: '0 15px 35px rgba(221,107,32,0.15)'
    },
    dark: {
      surface: '#141316',
      surfaceDim: '#0a090b',
      surfaceContainerLowest: '#030304',
      surfaceContainerLow: '#211f25',
      surfaceContainer: '#2d2b32',
      surfaceContainerHigh: '#3b3841',
      surfaceContainerHighest: '#4a4751',
      primary: '#ff7700',
      primaryContainer: '#662f00',
      primaryDim: '#ffa64d',
      onSurface: '#e2e2e5',
      outlineVariant: '#514d59',
      secondary: '#d2c4b1',
      secondaryContainer: '#423b30',
      onSecondaryContainer: '#f8f4ed',
      tertiary: '#c7c4b9',
      tertiaryContainer: '#35332e',
      radiusContainer: '12px',
      borderContainer: '2px solid var(--outline-variant)',
      shadowContainer: '0 12px 30px rgba(0,0,0,0.5)',
      transitionSpeed: '0.2s cubic-bezier(0.4, 0, 0.2, 1)',
      hoverTransform: 'scale(1.03)',
      hoverShadow: '0 15px 35px var(--primary)'
    }
  },
  'steampunk': {
    light: {
      surface: '#fbf5e6',
      surfaceDim: '#ebd9b4',
      surfaceContainerLowest: '#ffffff',
      surfaceContainerLow: '#f5edd4',
      surfaceContainer: '#ebd8bd',
      surfaceContainerHigh: '#dbc2a0',
      surfaceContainerHighest: '#cca783',
      primary: '#b87333',
      primaryContainer: '#ffebd8',
      primaryDim: '#7c4312',
      onSurface: '#2b1d0c',
      outlineVariant: '#bfa07e',
      secondary: '#7a5a3a',
      secondaryContainer: '#faebd7',
      onSecondaryContainer: '#2c1e0f',
      tertiary: '#415a77',
      tertiaryContainer: '#e0e6ed',
      radiusContainer: '12px',
      borderContainer: '4px solid var(--primary)',
      shadowContainer: 'inset 0 0 15px rgba(0,0,0,0.06), 0 10px 30px rgba(0,0,0,0.04)',
      transitionSpeed: '0.25s ease',
      hoverTransform: 'scale(1.02)',
      hoverShadow: '0 15px 40px rgba(184,115,51,0.12)'
    },
    dark: {
      surface: '#1e1711',
      surfaceDim: '#100c08',
      surfaceContainerLowest: '#060403',
      surfaceContainerLow: '#2c221a',
      surfaceContainer: '#392c21',
      surfaceContainerHigh: '#473729',
      surfaceContainerHighest: '#564332',
      primary: '#e5a93b',
      primaryContainer: '#5a3d00',
      primaryDim: '#ffd485',
      onSurface: '#ecd9c6',
      outlineVariant: '#5c4532',
      secondary: '#d4b491',
      secondaryContainer: '#473421',
      onSecondaryContainer: '#ecd9c6',
      tertiary: '#a3b18a',
      tertiaryContainer: '#344e41',
      radiusContainer: '12px',
      borderContainer: '4px solid var(--primary)',
      shadowContainer: 'inset 0 0 15px rgba(0,0,0,0.4), 0 10px 30px rgba(0,0,0,0.5)',
      transitionSpeed: '0.25s ease',
      hoverTransform: 'scale(1.02)',
      hoverShadow: '0 15px 40px rgba(184,115,51,0.2)'
    }
  }
};

export function getThemeStyles(preset: string, custom?: { light?: ThemeColorSet; dark?: ThemeColorSet }): string {
  const chosen = themePresets[preset] || themePresets['fantasy-parchment'];
  
  const light = { ...chosen.light, ...(custom?.light || {}) };
  const dark = { ...chosen.dark, ...(custom?.dark || {}) };

  const formatVariables = (colors: ThemeColorSet) => {
    return Object.entries(colors)
      .map(([key, value]) => {
        const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
        return `  --${cssKey}: ${value};`;
      })
      .join('\n');
  };

  const fontPreset = themeFonts[preset] || themeFonts['fantasy-parchment'];

  return `
:root {
${formatVariables(light)}
  --font-active-heading: ${fontPreset.heading};
  --font-active-body: ${fontPreset.body};
}

.dark {
${formatVariables(dark)}
  --font-active-heading: ${fontPreset.heading};
  --font-active-body: ${fontPreset.body};
}
  `.trim();
}
